### ISSUE TITLE
Drop support for Ruby <=1.9 (and perhaps 2.0?), focus on 2.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [steve8x8/geotoad#301]
```
Although Ruby 1.9 will be around for some more time, some Linux distributions 
are currently making the move to 2.0.x or even 2.1.x.
GeoToad needs to be tested with 2.1.x, and 1.9 support will be phased out in 
favour of adapting the code to 2.[01] sooner or later.
As a starting point, future releases will only receive Windows Installer 
packages including 2.0 (and 2.1, later on).
Please report any findings (possibly) related to the Ruby version here.
```

Original issue reported on code.google.com by `Steve8x8` on 17 Apr 2014 at 8:13

**Comment by steve8x8** [comment]
Just a quick remark on the current state: As I'm still stuck with WinXP for building Windows Installer packages, and Ruby >= 2.1 lacks support for XP (due to a missing symbol in one of the system libraries) I will continue to build ruby 2.0 packages for a while. As soon as I can put my hands on a Win7 license I may setup a VM using that. This may take a couple of months.
You say XP is outdated? Can't be, the trams here are still running on XP ;-) (well, rather the displays inside, but you never know)

**Comment by steve8x8** [comment]
In the not so far future, I'd like to experiment with Docker to handle both Windows and Mac builds. Anyone out there with a Docker 101 for me?
Still got to find a suitable W. version - for MacOS, I've been pointed to "osxcross", not sure whether that will cover all my needs, and I don't have a machine to test the result. If you feel like it, step forward to assist.
Thanks, S

**Comment by steve8x8** [comment]
Issue 326 seems to be related... Let's get rid of 1.9 soon, and of 2.0 soon thereafter.

**Comment by steve8x8** [comment]
3.25.0 (which has been flagged as the next Milestone) will require ruby >= 2.0, and recommend >= 2.1.
Also, Windows XP support will be dropped, and the Windows Installer package will be created using Ruby >= 2.1.5 (which is now available for recent Windows versions).
My next VM or build hardware (yet undecided) will be running Win 7, I won't be able to test Vista (does the 2.1 ruby-installer throw an error under Vista like it does under XP?)

**Comment by steve8x8** [comment]
After the migration of GC to https, and end-of-support for Windows XP, there's no real reason anymore to support Ruby <= 2.0 - the last version that worked with XP (and the VM that had been used to build the Windows Installer).

Yes, there will be no Win Installer anymore as long as I don't have access to a Win 7 VM. The last GeoToad release that came with a WI was 3.25.4.

The certificate chain will stay, but needs an update as well - or instructions how to get a recent version.

Windows users, please get your own Ruby installation (from rubyinstaller.org), get the GeoToad tarball and unpack it, and make sure you'll have the certificates in place - there are a few notes in the manual page (geotoad.pdf built from geotoad.1).

**Comment by steve8x8** [comment]
Ruby versions < 1.9.1 will result in an error, < 2.1.5 in a warning. Debian Stretch (9.5) has 2.3.3, Jessie (8.11) has 2.1.5 - no adverse effects have been found yet. Closing...
