### ISSUE TITLE
Mapping WID->GUID fails at first attempt if connection gone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [steve8x8/geotoad#314]
```
A very rare issue, only seen once in more than a hundred queries.
It's rather hard to reproduce this issue as it takes several prerequisites:
- a newly placed cache for which the mapping isn't known yet
- a temporarily broken internet connection

Unlike other accesses to the server, which have a retry count > 1, mapping 
currently fails if the first attempt isn't successful.

Restarting (after the connection has come back, of course) reliably fixes this 
issue, it's a bit annoying though, and should be fixed in the long run.
```

Original issue reported on code.google.com by `Steve8x8` on 20 Jan 2015 at 8:13

**Comment by steve8x8** [comment]
This is one of the most fragile parts of the code, and I'm rather unhappy with that. Although there are two strategies to determine the GUID that belongs to a WID, one of them stopped working (or never worked?), and the second one has no safeguarding against network outages. Of course, you can always restart your query, but it's annoying (and confusing to newcomers).
Suggestions welcome.

**Comment by steve8x8** [comment]
WID-to-GUID mapping has been rewritten, followup should go to Issue #335. Closing here.
