### ISSUE TITLE
Gemify this code?

### ISSUE THREAD

**Issue by miwest929** [steve8x8/geotoad#318]
Have you thought making a gem out of this repo and publishing to `rubygems.org`. Curious, why that hasn't been done yet. If you're interested I can do that for you.

**Comment by steve8x8** [comment]
Thanks for the idea - there had been a "geocaching" gem a couple of years ago indeed: https://rubygems.org/gems/geocaching/versions/0.8.1 but the original source repository has gone. I could find an early branch though: https://github.com/scjudd/ruby-geocaching
Given that gc.com is a moving target (which is especially true for searches, and cache detail representations) I'm rather unhappy with the idea of a Ruby gem, also I don't fully get it how to properly handle the GeoToad file cache in gem style.
If the geocaching gem was still maintained, it might indeed make GeoToad's life easier (although I'm not sure it would work with pre-built "executables" then - would Ocra be able to include other gems?)
But the source is open, there's a license attached to it - which basically means that nobody will stop you to publish "derived work" if you obey the rules. (You'd do that on your own, and for your own reputation. Go ahead if you feel like it.)

**Comment by steve8x8** [comment]
Any news about this? (Apparently not. Closing for now.)
