### ISSUE TITLE
Favorites count missing

### ISSUE THREAD

**Issue by SBejga** [steve8x8/geotoad#333]
Hi,

I just noticed that the favorite points count is missing. I only see  the fav factor in log created by geotoad (id -2)
Neither found in the exported gpx nor in the ruby object. Is it lost due format changes in gc.com? What do you think?

KR,
Sebastian

**Comment by steve8x8** [comment]
Did you use the last release or git head?

**Comment by SBejga** [comment]
I have used git head
Steve Sixty-Four <notifications@github.com> schrieb am So., 24. Jan. 2016
um 14:03:

**Comment by steve8x8** [comment]
Not sure whether I can address this before the upcoming release - TBH I'm surprised someone is actually using fav counts. For now, I blame the "Release 622" changes (for which there's no release notes). May I have your command line for tests?

**Comment by SBejga** [comment]
Surprised? Searching a bigger radius and then to sort by fav count is
great!
My "test" command line looks like that:
geotoad.rb -U -x gpx -o WID_from_GC2Q17Z_to_GC1GPN8.gpx -m , -q wid
GC2Q17Z,GC32MF4,GC1TYN6,GC1GPN8



Steve Sixty-Four <notifications@github.com> schrieb am Mo., 25. Jan. 2016
um 09:09 Uhr:

**Comment by SBejga** [comment]
Oh, the github mail ended at the pre code thing. So I did not get it when I clicked reply to in the mail client.

I am Premium Member and now a bit confused. I am sure that I have used the favorite count field already in my gpx exports. May I use a wrong command line option?

**Comment by SBejga** [comment]
Oops. Sorry I am wrong.
I was almost sure, that I have used it in that way already. Additionally I added a small debug console log to print the favorites of each fetched cache (directly in the ruby script). And there I got also no field values. At least it would be possible that, gc.com had some problems and was sending malformed html. I do not know. Or I just was tired or misspelled something...

Anyway, it works (again). Sorry for raising an issue.

But I will use the opportunity to thank you for a gread piece of software. It makes my Cacher life a lot of easier ;-)

best regards
Sebastian

**Comment by steve8x8** [comment]
```
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:D/T/S:  1/1/small, Fav: 0.0&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:    <gsak:FavPoints>9</gsak:FavPoints>
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:D/T/S:  1/2/micro, Fav: 0.0&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:    <gsak:FavPoints>2</gsak:FavPoints>
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:D/T/S:  1.5/1.5/micro, Fav: 1.2&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:    <gsak:FavPoints>35</gsak:FavPoints>
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:D/T/S:  2.5/2/regular, Fav: 0&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.cgpx:    <gsak:FavPoints>388</gsak:FavPoints>
WID_from_GC2Q17Z_to_GC1GPN8.gpx:D/T/S:  1/1/small, Fav: 0.0&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.gpx:D/T/S:  1/2/micro, Fav: 0.0&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.gpx:D/T/S:  1.5/1.5/micro, Fav: 1.2&lt;br /&gt;
WID_from_GC2Q17Z_to_GC1GPN8.gpx:D/T/S:  2.5/2/regular, Fav: 0&lt;br /&gt;
```
Note the "Fav: 0" for the last cache - although I can parse the number of given favpoints from the cache_details page, I have no access to the "icon counters", thus calculating a fav factor doesn't work - this is due to PMO. (There's not even a "Placed Date".)
Also note that a fav factor of 0.0 despite a fav count of 2 is due to a large number of visits - the formula is logarithmic, with 5.0 (max) for 100 fp's in 100 logs, about 2.5 for 10 in 100 (10 logs give you one fav point to spend as PM), and down to zero for 1 in 100 or even less.
