### ISSUE TITLE
Description is Empty for all Caches

### ISSUE THREAD

**Issue by PascalTurbo** [steve8x8/geotoad#357]
When using a simple query it results in an empty description for all caches.

```
./geotoad.rb --delimiter='|' --distanceMax=1 --format=gpx --output='/Users/christianbecker/Desktop/' --queryType=location --userExclude=PascalTurbo Niederlinxweiler
```

**Comment by steve8x8** [comment]
In a first attempt to reproduce this issue, Google Maps seems to be unable to resolve the location you provided. Do you have some center coordinates instead? - S

**Comment by steve8x8** [comment]
Using coord 49.4303610,7.1605613 and 1 mile radius, I get 15 caches, two of them Premium. I don't know your exclude list.
For all caches but the PMO ones, I have a description in my gpx output, using 3.28.1 without any patches. I suspect a disk full issue on your side (that may be several days old; cache details are kept for 5 days before overwriting them).
You're using the generic gpx format -what GPS device do you use? (I'm always looking for testers as I lost my Garmin years ago.) - S

**Comment by PascalTurbo** [comment]
I think I found the cause of the problem. The language of geocaching page for the premium account I'm using to fetch is set to german. When searching for caches using this german account and the long_description doesn't exist, it will have no description at all.

You can find the results for a search with german and english account here: https://gist.github.com/PascalTurbo/9279b81542c95753a655ae779f212510

PS: I have a garmin. I'm only using the default gpx format - nothing special.

**Comment by steve8x8** [comment]
I'm sorry, but I'm unable to check the responses in > 20 languages - I know that there had been an issue with Dutch a few years ago (search pages being formatted differently), but I cannot read Korean or Japanese at all (the log age detection has been built heuristically).
GeoToad shares the fate of other crawlers: it will fail if the crawled data structures change.
No promises that I will have the time to support more than English in the future - but I'll add a note to the manual page (and the ReportingBugs wiki page as well) along the lines of "if you see unexpected behaviour, like parsing errors or missing content, please switch the language to English on GC and retry".

**Comment by PascalTurbo** [comment]
I think there might be a better solution. Check, if language of response is english. If not, write an error or a warning that only english is supported by geotoad. So it's transparent, that there could be missing data by using other than english language.

**Comment by steve8x8** [comment]
Suggestion accepted. 3.28.3 will output warnings if it finds non-standard settings (for language and date-format).

**Comment by steve8x8** [comment]
3.28.3 has been released.
