### ISSUE TITLE
Command-line option --includeArchived is undocumented

### ISSUE THREAD

**Issue by IByte** [steve8x8/geotoad#358]
The command-line option --includeArchived (to force GT to output archived caches) is not documented in the command-line help, wiki or README file. I needed it and found it in the code (during an attempt to hack GT to do what I want). Please add it to the documentation. Thanks in advance.

(Oddly enough, -z for including disabled caches is documented.)

**Comment by steve8x8** [comment]
Are you talking about commit https://github.com/steve8x8/geotoad/commit/7cb3c47f9f62a9958e08927fa58bc5439235e0d2 dated April 24, 2016? The manual page (which gets converted to PDF) is there for a reason.
If you don't like that, send patches.

**Comment by steve8x8** [comment]
Perhaps the "usage" help is already too long, and since a manual page (a) exists and (b) is converted to PDF that one should be the major source of information?
