### ISSUE TITLE
Login fails (Oct 13, 2018)

### ISSUE THREAD

**Issue by steve8x8** [steve8x8/geotoad#361]
According to geo-* and c:geo changelogs, the 'Username' parameter for login has been renamed to 'UsernameOrEmail'. Until a new release of GeoToad is published, make the corresponding change to lib/auth.rb (line 146 for 3.28.2).

**Comment by steve8x8** [comment]
Closing after release of 3.28.3 which incorporates the fix.

**Comment by IByte** [comment]
Thanks for the fix. I just updated and Geotoad seems to work again. (Although the cache description appears to be missing, but that might be a problem with my own tool. I'll have to check.)
