### ISSUE TITLE
wishlist: get caches around a gpx track

### ISSUE THREAD

**Issue by cerisara** [steve8x8/geotoad#363]
When going for a bike trip, I often "follow" a gpx track. Getting all caches "around" the gpx track may be very convenient.

**Comment by steve8x8** [comment]
Duplicate of #103 from 2011 (!), see [the Wiki article](https://github.com/steve8x8/geotoad/wiki/OtherSearches#searches-along-a-given-track/route-issue-103).

This requires the command-line mode to be used.

Please be careful when defining what's "around" for you. A GPX track may be detailed or coarse, and usually requires resampling to achieve a more uniform point density along the track. Search radius and point distance must be somewhat balanced.
Also take into account that using this method you will miss most mystery caches in the vicinity.

Enjoy your bike trips!

**Comment by cerisara** [comment]
Thank you ! I didn't knew we could use geotoad programs in other scripts.
That's a great feature, may be not enough visible :)
Thanks...
