### ISSUE TITLE
Add support for Ruby 3.x (undefined method `escape' for URI:Module)

### ISSUE THREAD

**Issue by JP95Git** [steve8x8/geotoad#366]
Hi,

since Ruby 3 was released on 2020-12-25 and GeoToad doesn't say which version of Ruby is required, I tested Ruby 3.

I got this error
> undefined method `escape' for URI:Module
in lib/output.rb

It turns out, that URI.escape was already obsolete in Ruby 2.7 and it was removed in Ruby 3.0:
https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string

This is the line with URI.escape:
> coord_query = URI.escape(sprintf("%.6f,%.6f", cache['latdata'].to_f, cache['londata'].to_f))

**Comment by benmathews** [comment]
As a workaround, revert back to ruby 2.7. For ubuntu:

```
sudo snap install ruby --channel=2.7/stable --classic
```

**Comment by steve8x8** [comment]
I'm still running at Ruby 2.x (Debian Bullseye, for whatever reason, comes with 2.7). Pressure hasn't been high enough yet, and I've been busy with other projects.

I'll have another look at the issue and more - there's an occasional hiccup when GS provides a page that doesn't match the previous query, too. Stay tuned.

**Comment by freswa** [comment]
@steve8x8 #367 Works for ruby 2.7 and >= 3.0

**Comment by steve8x8** [comment]
Thanks for confirming - while I'm using a few versions of Ruby on different platforms, I couldn't upgrade to 3.x yet, so I'd rather play safe (and have a fallback to the old way should the new one fail, e.g. because of an old Ruby version).

I think it's time to get a new version out, perhaps with #368 also addressed... to fix this and #367.

**Comment by steve8x8** [comment]
Version 3.33.3, released some hours ago, incorporates the suggested change (plus a fallback to the old style, you never know...). Note that I'm still using Ruby 2.x on my two platforms, so this didn't get any real testing...
