### ISSUE TITLE
PMO cache recognition after Dec 10, with 3.34.0?

### ISSUE THREAD

**Issue by steve8x8** [steve8x8/geotoad#370]
Being a BM only, I see that there have been some changes on the site around Dec 10, affecting the translation of wids to guids.
While already known wids continue to be mapped to their guid via the entry in mapping.yaml, new ones may not work - certainly for BMs and even for PMs.
I'd like to get confirmation (or error reports, and possibly some assistance to dig into the details) from PMs:

Does geotoad continue to work, also with newly published caches?

Version 3.34.0, to be published later today, will add an output field (to selected formats only) that contains the mapping.yaml entry. That one could be "donated" to BMs to re-gain access to otherwise hidden information. Your feedback is essential to make this work, thanks!

**Comment by PascalTurbo** [comment]
Hi @steve8x8,

I've created a query for new caches from the last 20 days. I've used the current state of the master branch.

```./geotoad.rb --delimiter='|' --distanceMax=5 --format=gpx --output='/Users/christianbecker/Desktop/' -j 20 --queryType=location 'München'```

[query.tgz](https://github.com/steve8x8/geotoad/files/13833349/query.tgz)

A first quick look doesn't show me any problems.
Is this, what helps you?

**Comment by steve8x8** [comment]
Hi @PascalTurbo - I've been busy earning my living for a while so I only could have a closer look now.

All caches seem to be non-PMO ones, is this coincidence or did you search as Basic Member? Since I'm interested in what a PM would see about PMO caches, can you rerun with `-Q` aka `--onlyPMO`, possibly dropping the `-j` option in favour of a smaller `-y` distance?

**Comment by steve8x8** [comment]
In case anyone feels the need to support my work: there's a buymeacoffee.com link on my profile page now. It says "book" instead of "coffee" now, but I'd attempt to get hold of a Premium membership for a month if that's still possible.

**Comment by PascalTurbo** [comment]
@steve8x8: As you can see, I'm also less responsive.

I ran that query because I thought, only newly created cashes are relevant. So I've searched a bit to find a cache that was placed in 2024 and is PMO. I've droped the -j and run the following query:


`./geotoad.rb --delimiter='|' --distanceMax=3 --format=gpx --output='/Users/christianbecker/Desktop/' --queryType=location 'Landshut' -Q`

There should be at least the cache [GCAJ2EV](https://www.geocaching.com/geocache/GCAJ2EV).

Here the results:

[PMO.tgz](https://github.com/steve8x8/geotoad/files/13942864/PMO.tgz)

**Comment by steve8x8** [comment]
> @steve8x8: As you can see, I'm also less responsive.

Hey, we all got a Real Life somewhere, don't we?  ;)

> I ran that query because I thought, only newly created cashes are relevant.

Only newly "found" (in terms of searching on gc.com) ones, because the information for old, already "seen" ones is kept in the mapping file.

> There should be at least the cache [GCAJ2EV](https://www.geocaching.com/geocache/GCAJ2EV).

GC4QF89 is - and apparently the information I was looking for is there. (Plus there's confirmation that PMs will see PMO caches with the [$] flag, and - because there's a description available, that will be presented as [$+], in case you've been wondering what that stuff means. There's a [m] flag as well...)

Thanks a lot, I'm pretty sure now that - while the milestone is still being worked on - PMs don't have any disadvantages compared to BMs.

**Comment by steve8x8** [comment]
For those who want to help out their friends with extra mapping entries: The released version already contains a `wp2guid` template that contains the mapping, just not in a format that would be accepted as yaml :(
