### ISSUE TITLE
Geotoad web-ui

### ISSUE THREAD

**Issue by GoogleCodeExporter** [steve8x8/geotoad#75]
```
Hello, i have created a web-ui for geotoad. Would you be please so kind to
put the sources on this project? Please contact me on the mail
zbytovsky@gmail.com
Pavel
```

Original issue reported on code.google.com by `zbytov...@gmail.com` on 6 Oct 2009 at 8:41

**Comment by steve8x8** [comment]
Anyone willing to work on this?

**Comment by steve8x8** [comment]
Given the age of this issue, and the shrinking user-base of GeoToad, I'm closing.
I think we lost most users to apps, and yet another web interface wouldn't help...

To be honest, I lost my 6-year old Garmin a year ago, but I'm still building GPX files - to be imported into c:geo for Android - and POI for the street nav device, but I'm doing that in a PQ-like manner, from the command-line. If you need to have a quick look, the TUI is slim and efficient (but lacks some features); if you want to get any further there's nothing that can replace the CLI.
Again, if you think different: we're living in an Open world (but please let me know).
